apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  selector:
    app: result
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5001
    - name: debugger
      protocol: TCP
      port: 9229
      targetPort: 9229

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: enzokrr/esiea-ressources-result:v1

